### ISSUE TITLE
Org Team Approver Documentation Issue

### ISSUE THREAD

**Issue by obalyuk87** [trstringer/manual-approval#102]
Thank you for creating and sharing an amazing plugin! 

The docs on the "Org Team Approver" have limited / incorrect information, the the extra "Permissions" section is misleading.
https://github.com/marketplace/actions/manual-workflow-approval#org-team-approver

I followed the docs for Team Approver setup but pipeline was failing with error below
```

Required approvers: [user1 user2 user3]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.
error creating issue: POST https://api.github.com/repos/my-org/misc-prototypes/issues: 403 Resource not accessible by integration []
```

In case of explicitly listed users the `trstringer/manual-approval@v1` step is executed with `secret: ${{ github.TOKEN }}`. However in case of Org Team Approver `secret: ${{ steps.generate_token.outputs.token }}` is used. Per docs, the GitHub app was created with **read-only access to organization members**, which is not enough to create an issue in the repo. Once I added "Issues Write" permission to the GitHub app - the workflows worked as expected!

App Permissions
<img width="525" alt="image" src="https://github.com/trstringer/manual-approval/assets/7018369/f21123dd-2e93-456b-9790-36bc5bf20e33">

**Comment by rjcoupe** [comment]
I ran into the same problem and came to the same solution.

**Comment by afrazkhan** [comment]
It works for me with the additional permission up until the actual approval message, which never gets picked up. Issue is created, and even cancelled when the run is cancelled manually, but replying to the created issue with an approved response never gets picked up by the action.

I've tried adding the "Issue comment" event to the permissions, which seems like an obvious necessity, but still no joy.

**Comment by cwong-archy** [comment]
i have this issue. i have set the github app with the correct permissions (i think)
<img width="777" alt="Screenshot 2024-10-24 at 4 26 08 PM" src="https://github.com/user-attachments/assets/b5dd491a-9486-4b81-8a33-f18f2c0c2ffe">
<img width="763" alt="Screenshot 2024-10-24 at 4 26 26 PM" src="https://github.com/user-attachments/assets/20bd10bb-8b3c-4f62-9d47-c81304dbb39e">

but still getting -
```
Required approvers: [eng-release]

Respond "approved", "approve", "lgtm", "yes", "ok", "lfg", "ship it" to continue workflow or "denied", "deny", "no" to cancel.
error creating issue: POST https://api.github.com/repos/ORG/REPO/issues: 403 Resource not accessible by integration []
```

my gha -
```
  wait-for-approval:
    runs-on: self-hosted-deploy-dev
    steps:
      - id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GHA_WAIT_FOR_APPROVAL_APPID }}
          private_key: ${{ secrets.GHA_WAIT_FOR_APPROVAL_PRIVATE_KEY }}
      - id: manual-approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ steps.generate-token.outputs.token }}
          approvers: eng-release
          minimum-approvals: 1
          additional-approved-words: ok,lfg,ship it
```

**Comment by snskArora** [comment]
Updating the README, thank you for pointing it out.

@cwong-archy Sometimes the org security keeps a few permissions off, which are by default granted to a workflow. Please try by giving id-token: write, contents: read permissions.

**Comment by cwong-archy** [comment]
> Updating the README, thank you for pointing it out.
> 
> [@cwong-archy](https://github.com/cwong-archy) Sometimes the org security keeps a few permissions off, which are by default granted to a workflow. Please try by giving id-token: write, contents: read permissions.

@snskArora i have the permissions as indicated -
```
name: backend-group-installer-prod

on:
  workflow_dispatch:
    inputs:
      group_job_trigger:
        type: string
        description: 'Are you sure you want to trigger the workflow? (yes/no)'
        required: true

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write
  issues: write
  checks: write

jobs:
  call-backend-api-canary-installer:
    uses: ./.github/workflows/backend-canary-installer-prod.yml
    ...
  wait-for-approval:
    ...
```

**Comment by snskArora** [comment]
Can you please check if issues are enabled fir the repo.
This is the only other thing that comes to mind

**Comment by cwong-archy** [comment]
> > Can you please check if issues are enabled fir the repo. This is the only other thing that comes to mind
> 
> OMG.. thank you!!! turned out it was a human error from our end!!! 🤦🏻‍♂️ the owner of the org needed to approve the access request!!!
> 
> before it was only `read access to metadata` - <img alt="Image" width="574" src="https://private-user-images.githubusercontent.com/113930223/456244655-f3655023-5723-4a9d-be0e-2e995fe8330f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAyMDMzMjEsIm5iZiI6MTc1MDIwMzAyMSwicGF0aCI6Ii8xMTM5MzAyMjMvNDU2MjQ0NjU1LWYzNjU1MDIzLTU3MjMtNGE5ZC1iZTBlLTJlOTk1ZmU4MzMwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYxN1QyMzMwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDdmNWZkZjhjOTNkMDE1YTYyMmU1MTJkM2ZhMzgxMGFhMThmYzJkYTAwNmE1NDRkYTVkZWFjOTVmN2MwM2I5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mpuHvfXCUIVthss6SwuU8E8MsktVygnSfBpTLDWWOrI">

***recap*** -

app -
read access to actions, members, and metadata
read and write access to issues

yml file -
```
...
permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write
  issues: write
  checks: write
...
  wait-for-approval:
    runs-on: self-hosted-deploy-dev
    needs: call-backend-api-canary-installer
    steps:
      - id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GHA_WAIT_FOR_APPROVAL_APPID }}
          private_key: ${{ secrets.GHA_WAIT_FOR_APPROVAL_PRIVATE_KEY }}
      - id: manual-approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ steps.generate-token.outputs.token }}
          approvers: eng-release
          minimum-approvals: 1
          issue-title: "Deploying backend-api from canary to main"
          additional-approved-words: ok,lfg,ship it
...
```
