### ISSUE TITLE
Permission Denied at step start

### ISSUE THREAD

**Issue by wasuaje** [trstringer/manual-approval#105]
This is the output from my workflow at the very beginning: 
```

/usr/bin/docker pull ghcr.io/trstringer/manual-approval:1.9.0
  permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.2[4](https://github.com/wasuaje/fastERPTodocaser/actions/runs/5647730094/job/15298594526#step:2:4)/images/create?fromImage=ghcr.io%2Ftrstringer%2Fmanual-approval&tag=1.9.0": dial unix /var/run/docker.sock: connect: permission denied
```

the code

```
    steps:
      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.9.0
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: wasuaje
          minimum-approvals: 1
```

any suggestion?

**Update**: I think the issue it is trying to run /usr/bin/docker, for security reasons github runner is in a non-proviledge user which only has SUDO docker access, so I usually make "sudo docker xxxx yyy zzz". This action points to "/usr/bin/docker". Any way to bypass this config? 

I tried hard to make aliases, through .env file setting up a pre-run script, which seems to work (alias docker='sudo docker') At SO level works, and run setup shows it works, but somehow can't make it work with this action.

Any help is appreciated
