### ISSUE TITLE
422 Validation Failed [{Resource:Issue Field:assignees Code:invalid Message:}]

### ISSUE THREAD

**Issue by ashishjullia** [trstringer/manual-approval#109]
Used the following values for github team and token:
![image](https://github.com/trstringer/manual-approval/assets/11252951/ef602501-9d44-4d6f-9d49-3c59b388dcd8)

But I'm getting the following error:
Note: The same setup was working in other repo 2 days back but today I created a new repo but not working.

`error creating issue: POST https://api.github.com/repos/EQWorks/eq-mwaa/issues: 422 Validation Failed [{Resource:Issue Field:assignees Code:invalid Message:}]`

**Comment by ashishjullia** [comment]
So for the same setup, one repo was able to expand the github team for the list of users and was able to create an issue tagging them but this new repo with the same setup wasn't able to create an issue with same team but when I specifically mentioned user names then the issue was resolved, I'm not sure why this behavior.

**Comment by wangxued** [comment]
Yes, I have some issue on this
```

  wait-for-approval:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    needs: [get-some-vars,build-to-acr,deploy-to-sit1]
    steps:
      - uses: trstringer/manual-approval@v1
        env:
          current_version: ${{ needs.get-some-vars.outputs.release_number }}
        with:
          secret: ${{ github.TOKEN }}
          approvers: user01,user02,team01
          minimum-approvals: 1
          issue-title: "Deploying ${{ env.current_version }} to pre"
          issue-body: "Please approve or deny the deployment of version ${{ env.current_version }}."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
```

**Comment by iarovyi** [comment]
I got the same problem: `error creating issue: POST https://api.github.com/repos/xxx/xxx/issues: 422 Validation Failed [{Resource:Issue Field:assignees Code:invalid Message:}]`

The code used:
```yml
    - name: Approval
      uses: trstringer/manual-approval@dd1555b1d17966cb58500676d79a181c53bb6c12
      with:
        secret: "......."
        approvers: "my-group"
        minimum-approvals: 1
        issue-title: "......"
        issue-body: "......"
        exclude-workflow-initiator-as-approver: false
```

It used to work and suddenly it broke when new user was added  to the group. I tested it on multiple repositories and all comes down to single specific user. If group has this user or this user is specified directly than it fails.
