### ISSUE TITLE
Approvers as env variable

### ISSUE THREAD

**Issue by djordjevicdjordje** [trstringer/manual-approval#119]
Is it possible to set approvers to be read from the environment variable?

Its much easier to update the variable than to change the workflow each time I want to add new approver

**Comment by erjdev** [comment]
You could set the value as an environment variable then access it in the call to this action.  This action does not need to support environment variables to accomplish your goal.

```yml
# my-workflow.yml
name: 'My Workflow'
#...
env:
  APPROVERS: user1,user2
#...
jobs:
  my-job:
    #...
    steps:
      #...
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 15
        with:
          approvers: ${{ env.APPROVERS }}
          #...
```
