### ISSUE TITLE
Confused about timeout for manual-approval 72 hours or 6 hours?

### ISSUE THREAD

**Issue by thardy** [trstringer/manual-approval#135]
I posted this on StackOverflow and haven't seen any knowledgeable responses...

The documentation mentions...

> "Note: This approval duration is subject to the broader 72 hours timeout for a workflow. So keep that in mind when figuring out how quickly an approver must respond."

Then a little further down it states...

> "A job (including a paused job) will be failed after 6 hours"

I find the above two statements to be incredibly confusing. How long would someone have to approve, 72 hours or 6 hours? How can someone have 72 hours to approve if the job is automatically failed after 6 hours? What is the difference between the two timeouts? Can I get a little more detail on what scenarios define each?

I'm hesitant to even try this action because it sounds like it will just constantly burn through usage limits.

**Comment by lizziemac** [comment]
> I'm hesitant to even try this action because it sounds like it will just constantly burn through usage limits.

You can set your own timeout as well, using the GitHub actions `timeout-minutes`. I've also found that if you let the action timeout, and then want to re-run everything from the approval process onwards, you can just `re-run failed jobs` and the workflow will pick up where it left off, maintaining the outputs it retrieved from previous jobs.

```yaml
      - name: Await approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 5
        continue-on-error: false # specifically for timeouts, we WANT to mark the job as failed so that we can 're-run failed jobs' and pick up where we left off
        with:
             # ...
```
