### ISSUE TITLE
issue assignee setting

### ISSUE THREAD

**Issue by stefanolaru** [trstringer/manual-approval#144]
Hi, thanks a lot for creating this, it's very useful.

I have the following problem, no matter who triggers the workflow the issues are always assigned to me (user_4).

I have the workflow step set like this:

```
- uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: user_1,user_2,user_3,user_4
        minimum-approvals: 1
```

I'm the admin of the repo, but so is one of the other approvers.

Is this normal behavior? Shouldn't the issue be assigned to all the approvers?
