### ISSUE TITLE
Unable to use `fail-on-denial: false`  flag

### ISSUE THREAD

**Issue by milan-dangol** [trstringer/manual-approval#166]
- [ ] I have searched through the current issues and did not find any that were related.

**Describe the bug**
Unable to use `fail-on-denial: false` flag 

**To Reproduce**

```
      - name: Manual Approval
        id: manual-approval
        uses: trstringer/manual-approval@main
        with:
          secret: ${{ secrets.TOKEN }}
          minimum-approvals: 1
          issue-title: "Approval Required "
          issue-body: |
            Please review the code:
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: 'approved,lgtm,yes'
          additional-denied-words: 'denied,no'
          approvers: ${{ inputs.approver }}
          fail-on-denial: false
```

**Expected behavior**

**Screenshots**

![Image](https://github.com/user-attachments/assets/79c5652e-e320-45ed-9752-9c4ef807e112)

![Image](https://github.com/user-attachments/assets/bcfbf18b-fd0e-4927-9597-da06c74363b8)

**Additional context**
