### ISSUE TITLE
Manual Workflow Approval action outputs are empty

### ISSUE THREAD

**Issue by MathewStylianidis** [trstringer/manual-approval#171]
- [X] I have searched through the current issues and did not find any that were related.

**Describe the bug**

I am trying to access the outputs of the manual approval github action in subsequent steps, so that I can read the comments written by the reviewers. However, the outputs are empty.

I am using the latest commit from the main branch as of now: ef4dddd64bf9eca035ffe51d23f12d20e3a83613

**To Reproduce**

Change the approvers username and make workflow with the job below:

```
jobs:
  ManualApprovalWorkflow:
    name: manual approval workflow
    runs-on: ubuntu-latest
    steps:
        # Pause the workflow, creating a manual approval issue that can be used to resume it later
      - name: Await Approval
        id: workflow_approval
        uses: trstringer/manual-approval@ef4dddd64bf9eca035ffe51d23f12d20e3a83613
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: user1
          minimum-approvals: 1
          issue-title: 'Workflow Review'
          issue-body: |
            Lorum Ipsum
            bla bla bla

      - name: Access Manual Approval Issue
        run: |
          ISSUE_NUMBER="${{ steps.workflow_approval.outputs.issue-number }}"
          echo $ISSUE_NUMBER
          echo ${{ toJson(steps.workflow_approval.outputs) }}
```

**Expected behavior**
I expected the Access Manual Approval Issue to print out the issue number or at least some other output. However, outputs is empty.
