### ISSUE TITLE
fail-on-denial not working as expected

### ISSUE THREAD

**Issue by digorgonzola** [trstringer/manual-approval#177]
- [x] I have searched through the current issues and did not find any that were related.

**Describe the bug**
When defining `fail-on-denial: false` I expect the workflow to continue without error but this is not the behaviour I am getting.

**To Reproduce**
1. Set up your approval step:
```
      - uses: trstringer/manual-approval@bfb0ba38d02a528a2c101381809dc6c3062732c1
        id: approval
        with:
          secret: ${{ github.token }}
          approvers: user1
          minimum-approvals: 1
          fail-on-denial: false
```
2. Deny the approval in the issue

**Expected behavior**
I expect the workflow to continue running the following steps.

**Screenshots**

![Image](https://github.com/user-attachments/assets/18d71709-5ee1-4fd0-a3ec-d3e7ddbb6217)

![Image](https://github.com/user-attachments/assets/0046dae4-3c0c-4276-bb66-a1a4b82166a4)

**Additional context**
