### ISSUE TITLE
Issue to approve/decline is not closed automatically

### ISSUE THREAD

**Issue by iuriipaniukov** [trstringer/manual-approval#30]
We are using the action with those props:
```
- uses: trstringer/manual-approval@v1
      with:
          secret: ...
          approvers: ...
          issue-title: ...
```
but after a job is declined I expect the issue should be closed automatically if there were no reaction. Unfortunately, some of them are not closed.

What might be the issue?

Thank you!
