### ISSUE TITLE
Unexpected input(s): 'timeout-minutes'?

### ISSUE THREAD

**Issue by sheeeng** [trstringer/manual-approval#48]
```text
Unexpected input(s) 'timeout-minutes', valid inputs are ['entryPoint', 'args', 'approvers', 'secret', 'minimum-approvals', 'issue-title']
```

Timeout argument is not recognised in GitHub Actions.

```yaml
  - uses: trstringer/manual-approval@v1
    with:
       timeout-minutes: 5
````

Also, see #47.
