### ISSUE TITLE
Unable to Expand Org Team 

### ISSUE THREAD

**Issue by gthomson31** [trstringer/manual-approval#55]
Hi There 

Currently utilising this action within a new pipeline and have ran into the following issue.
This works when using individual org users but not team names.

```
      - name: Generate Approval token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GLOBAL_WORKFLOW_APPROVAL_APP_ID }}
          private_key: ${{ secrets.GLOBAL_WORKFLOW_APPROVAL_APP_PRIVATE_KEY }}

      - name: Wait for execution approval
        id: procceed-with-execution-of-aws-sandbox-nuke
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ steps.generate_token.outputs.token }}
          approvers: ${{ env.GITHUB_TEAM_NAME }}
          minimum-approvals: 1
          issue-title: "${{ github.action }}" # optional - default is "Manual Approval"
```

```
Attempting to expand user snowplow-devops/com.snowplowanalytics.engineeringproductivity as a group (may not succeed)
GET https://api.github.com/orgs/snowplow-devops/teams/com.snowplowanalytics.engineeringproductivity/members: 404 Not Found []
Creating issue in repo snowplow-devops/engineering-productivity with the following content:
Title: Manual approval required for workflow run 3368332814: procceed-with-execution-of-aws-sandbox-nuke

```

Any help appreciated!
