### ISSUE TITLE
In a Sleep-host-Runner environment, error retrieving approvers: error parsing exclude-workflow-initiator-as-approver flag: strconv.ParseBool: parsing "": invalid syntax  An error will occur

### ISSUE THREAD

**Issue by jieey1140** [trstringer/manual-approval#67]
The following error occurs.

`error retrieving approvers: error parsing exclude-workflow-initiator-as-approver flag: strconv.ParseBool: parsing "": invalid syntax`

my workflow step: 
 ```
           - uses: trstringer/manual-approval@v1
              with:
                  secret: ${{ github.TOKEN }}
                  approvers: jieey1140
                  minimum-approvals: 1
                  issue-title: 'Deploying Production'
```

self-host-runner ENV: 

OS: Ubuntu 22.04
Docker: Installed.

I need your help!
