### ISSUE TITLE
422 Validation Failed

### ISSUE THREAD

**Issue by zubrik13** [trstringer/manual-approval#71]
Latest runs fails with following error msg
```
error creating issue: POST https://api.github.com/repos/*/*/issues: 422 Validation Failed [{Resource:Issue Field:assignees Code:invalid Message:}]
```
Full error message:
```
Creating issue in repo smartlook/smartlook-devops with the following content:
Title: Manual approval required for workflow run 11111111: Terraform deployment to prod environment
Approvers: [user1 user2 user3]
Body:
Workflow is pending manual review.
URL: https://github.com/smartlook/smartlook-devops/actions/runs/11111111

Required approvers: [user1 user2 user3]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.
error creating issue: POST https://api.github.com/repos/*/*/issues: 422 Validation Failed [{Resource:Issue Field:assignees Code:invalid Message:}]
```

Use it in following configuration:
```
- name: Manual approval
  id: approve
  uses: trstringer/manual-approval@v1
  timeout-minutes: 1
  with:
    secret: ${{ github.TOKEN }}
    approvers: user1,user2,user3
    minimum-approvals: 1
    issue-title: "Terraform deployment to ${{ matrix.env }} environment"
    exclude-workflow-initiator-as-approver: false
```

Discovered it today. Worked flawless previously.

Any ideas regarding the reason?

Thanks
