### ISSUE TITLE
Unexpected input(s): 'timeout-minutes'? #48

### ISSUE THREAD

**Issue by JagannathGouda07** [trstringer/manual-approval#77]
Hi,
I am using `trstringer/manual-approval@v1` in my github actions and observed that I am receiving annotation warnings for `issue-body`.

```
     uses: trstringer/manual-approval@v1
     with:
        secret: ${{ github.TOKEN }}
        approvers: user1,user2
        minimum-approvals: 1
        issue-title: 'Deploying to prod'
        issue-body: 'Please approve or deny the prod deployment'
        exclude-workflow-initiator-as-approver: false
```

```
Unexpected input(s) 'issue-body', valid inputs are ['entryPoint', 'args', 'approvers', 'secret', 'minimum-approvals', 'issue-title', 'exclude-workflow-initiator-as-approver']
```
Any suggestions would be helpful.
