### ISSUE TITLE
Add individual members in a github team/org

### ISSUE THREAD

**Issue by ashishjullia** [trstringer/manual-approval#91]
Hi @trstringer 

I'm not sure whether this is possible or not without a PAT but I want to add individual members under a particular org.
- not complete org
- not a team
- but only a single member -> I'm not sure whether the action also works on members without considering them as a part of org/team

```yml
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: user1,user2,user3
          minimum-approvals: 1
```

I'm getting the following error:
```
Attempting to expand user <org-name>/<user1> as a group (may not succeed)
GET https://api.github.com/orgs/<org-name>/teams/<user1>/members: 404 Not Found []
```

Let me know if I'm missing something.

Any help is appreciated.
