### ISSUE TITLE
GitHub Issues can only have up to 10 people assigned to a issue

### ISSUE THREAD

**Issue by vincentclee** [trstringer/manual-approval#94]
## Example Config
```yml
steps:
  - uses: trstringer/manual-approval@v1
    with:
      secret: ${{ github.TOKEN }}
      approvers: org-team1
```

If your `org-team1` has more than 10 users, only 10 users will be added to the issue. The workflow does not generate a error. This limitation should be documented.

--- 

<img width="1259" alt="Screenshot 2023-04-19 at 3 37 25 PM" src="https://user-images.githubusercontent.com/5388077/233181759-b55ff445-1295-4cc2-9d04-8e563fce5466.png">
