### ISSUE TITLE
Pausing is very cost expensive

### ISSUE THREAD

**Issue by Uzlopak** [trstringer/manual-approval#95]
Please add a warning, that using this action is pausing a github runner. So if you use private repos, you get heavily billed.

**Comment by cristianmadularu** [comment]
> Please add a more prominent warning, that using this action is pausing a github runner. So if you use private repos, you get heavily billed.

Do you know if using the native support for gating environments would also incur additional costs? (other than the more expensive monthly subscription cost). Thanks!

**Comment by Uzlopak** [comment]
@cristianmadularu 
What do you mean with gating environment? 
Are you referring to this?
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#wait-timer

If so I have no clue. We have a github enterprise account, so we dont use wait-timers.

**Comment by cristianmadularu** [comment]
I was refering to this
https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments

It is only available with github enterprise (which we do not have) and I was looking for alternatives - which is what led me to this potential workaround (the manual-approval action).

**Comment by Uzlopak** [comment]
I can not test it rn.

You can use following rule of thumb:

For every job (not step) started a new github runner is spawned. And from that moment the billing starts. This action is a step in a job runner. And the step stops on some Thats why it is expensive in private repos.

You can test that reviewing deployments functionality. If you see in the action overview, that a job is running, it means that you are creating billing minutes. 

Afaik, the deployment reviewing function does not start a job but waits till somebody approved the run of the ci cd pipeline. 

What is your use case? Maybe you dont need to use this action at all. E.g. trigger manually the deployment workflows by adding a label to the pr. 

```yaml
name: Deploy on Staging and run tests

on:
  pull_request_target:
    types: [labeled]

jobs:
  benchmark:
    if: ${{ github.event.label.name == 'test-staging' }}
    runs-on: ubuntu-latest
    steps:
      ...
```
